"""drop unused JiraCredential.updated_at

Revision ID: 7c09c5a0010d
Revises: a1b2c3d4e5f6
Create Date: 2026-07-15 20:43:19.719015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c09c5a0010d'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jira_credentials', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('jira_credentials', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                'updated_at',
                sa.DATETIME(),
                nullable=False,
                server_default=sa.func.current_timestamp(),
            )
        )

    # ### end Alembic commands ###
